# Compose file for Alastria RedT node
services:
  alanode:

    # Build our image so we control the environment
    build: .

    # Use "validator", "regular" or "boot" so tools could use those names
    # But you can use whatever container name you wish for your environment
    container_name: "regular"

    # Enable the container to restart automatically after node reboot, for example
    restart: unless-stopped

    # Extend the period that Docker uses (10s by default) for killing forcefully the process
    # This is needed so Geth can have enough time to flush its caches
    stop_grace_period: 2m

    volumes:
      # Map the current directory to an internal one so Geth can store the chain in the docker host
      - ".:/root/alastria"

    ports:
      # For P2P comms
      - "21000:21000/tcp"
      - "21000:21000/udp"

      # For HTTP JSON-RPC from clients
      - "22000:22000"

      # For WebSocket JSON-RPC clients.
      # Separate from HTTP so specific firewall rules can be applied easily.
      - "22001:22001"
